# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Stor3d.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boxLength = QtWidgets.QLineEdit(self.centralwidget)
        self.boxLength.setAlignment(QtCore.Qt.AlignCenter)
        self.boxLength.setObjectName("boxLength")
        self.verticalLayout_2.addWidget(self.boxLength)
        self.boxWidth = QtWidgets.QLineEdit(self.centralwidget)
        self.boxWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.boxWidth.setObjectName("boxWidth")
        self.verticalLayout_2.addWidget(self.boxWidth)
        self.boxHeight = QtWidgets.QLineEdit(self.centralwidget)
        self.boxHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.boxHeight.setObjectName("boxHeight")
        self.verticalLayout_2.addWidget(self.boxHeight)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.lengthLabel.setObjectName("lengthLabel")
        self.verticalLayout.addWidget(self.lengthLabel)
        self.widthLabel = QtWidgets.QLabel(self.centralwidget)
        self.widthLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widthLabel.setObjectName("widthLabel")
        self.verticalLayout.addWidget(self.widthLabel)
        self.heightLabel = QtWidgets.QLabel(self.centralwidget)
        self.heightLabel.setObjectName("heightLabel")
        self.verticalLayout.addWidget(self.heightLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slottedCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.slottedCheckBox.setEnabled(False)
        self.slottedCheckBox.setObjectName("slottedCheckBox")
        self.horizontalLayout_3.addWidget(self.slottedCheckBox)
        self.gridLength = QtWidgets.QLabel(self.groupBox)
        self.gridLength.setEnabled(False)
        self.gridLength.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLength.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLength.setObjectName("gridLength")
        self.horizontalLayout_3.addWidget(self.gridLength)
        self.gridX = QtWidgets.QLabel(self.groupBox)
        self.gridX.setEnabled(False)
        self.gridX.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridX.setAlignment(QtCore.Qt.AlignCenter)
        self.gridX.setObjectName("gridX")
        self.horizontalLayout_3.addWidget(self.gridX)
        self.gridWidth = QtWidgets.QLabel(self.groupBox)
        self.gridWidth.setEnabled(False)
        self.gridWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.gridWidth.setObjectName("gridWidth")
        self.horizontalLayout_3.addWidget(self.gridWidth)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.lengthCellSlider = QtWidgets.QSlider(self.centralwidget)
        self.lengthCellSlider.setEnabled(False)
        self.lengthCellSlider.setMinimum(1)
        self.lengthCellSlider.setMaximum(10)
        self.lengthCellSlider.setProperty("value", 1)
        self.lengthCellSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lengthCellSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.lengthCellSlider.setTickInterval(1)
        self.lengthCellSlider.setObjectName("lengthCellSlider")
        self.verticalLayout_3.addWidget(self.lengthCellSlider)
        self.widthCellSlider = QtWidgets.QSlider(self.centralwidget)
        self.widthCellSlider.setEnabled(False)
        self.widthCellSlider.setMinimum(1)
        self.widthCellSlider.setMaximum(10)
        self.widthCellSlider.setOrientation(QtCore.Qt.Horizontal)
        self.widthCellSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.widthCellSlider.setTickInterval(1)
        self.widthCellSlider.setObjectName("widthCellSlider")
        self.verticalLayout_3.addWidget(self.widthCellSlider)
        self.renderDimensions = QtWidgets.QPushButton(self.centralwidget)
        self.renderDimensions.setEnabled(False)
        self.renderDimensions.setObjectName("renderDimensions")
        self.verticalLayout_3.addWidget(self.renderDimensions)
        self.generateSTLFile = QtWidgets.QPushButton(self.centralwidget)
        self.generateSTLFile.setEnabled(False)
        self.generateSTLFile.setObjectName("generateSTLFile")
        self.verticalLayout_3.addWidget(self.generateSTLFile)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.insert_picture = QtWidgets.QLabel(self.centralwidget)
        self.insert_picture.setMinimumSize(QtCore.QSize(375, 375))
        self.insert_picture.setAlignment(QtCore.Qt.AlignCenter)
        self.insert_picture.setObjectName("insert_picture")
        self.horizontalLayout_2.addWidget(self.insert_picture)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 545, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STOR3D"))
        self.label.setText(_translate("MainWindow", "Objects with dimensions bigger than \"23\" in any category may not render properly"))
        self.boxLength.setPlaceholderText(_translate("MainWindow", "Length"))
        self.boxWidth.setPlaceholderText(_translate("MainWindow", "Width"))
        self.boxHeight.setPlaceholderText(_translate("MainWindow", "Height"))
        self.lengthLabel.setText(_translate("MainWindow", "Inches (L)"))
        self.widthLabel.setText(_translate("MainWindow", "Inches (W)"))
        self.heightLabel.setText(_translate("MainWindow", "Inches (H)"))
        self.slottedCheckBox.setText(_translate("MainWindow", "Cells?"))
        self.gridLength.setText(_translate("MainWindow", "1"))
        self.gridX.setText(_translate("MainWindow", "x"))
        self.gridWidth.setText(_translate("MainWindow", "1"))
        self.renderDimensions.setText(_translate("MainWindow", "Render Dimensions"))
        self.generateSTLFile.setText(_translate("MainWindow", "Generate 3D File"))
        self.insert_picture.setText(_translate("MainWindow", "Click \"Render Dimensions\" Button to Display Box Here..."))

